### ISSUE TITLE
在本地，使用minikube，完成hello1内部调用hello2

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#39]
## 目标
本地k8s环境使用minikube。
hello1运行两个pod，能够向cluster外部提供服务。
hello2运行两个pod，仅能够在cluster内部提供服务。
在本地环境中，请求hello1的接口，在hello1中以service name的方式请求hello2的接口。
hello1与hello2的代码已完成，并以打成镜像上传至私有的镜像仓库中。

### 创建k8s拉取镜像所需的secret
使用下列命令创建secret，将下列的镜像仓库地址、用户名、密码换成实际内容。
参数docker-registry表示使用docker镜像仓库。
参数registry-tencent是自定义的secret的名字，用于写在部署文件的imagePullSecrets设置项上，表示采用该secret。
```
kubectl create secret docker-registry registry-tencent --namespace=default \
    --docker-server=镜像仓库地址 --docker-username=用户名 \
    --docker-password=密码
```
创建结果：
```
secret/registry-tencent created
```
#### 本地目录结构。
```
.
|
|---hello
| |---depoly
| | |---hello2
| | | |---deployment.yaml
| | | |---service.yaml
| | |---hello1
| | | |---deployment.yaml
| | | |---service.yaml
```
#### hello1的部署文件
hello1的deployment.yaml文件内容。
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1 
  namespace: default
  labels:
    app: hello1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello1
  template: 
    metadata: 
      labels: 
        app: hello1 
    spec:
      containers: 
      - name: hello1
        image: shgbit.tencentcloudcr.com/hello/hello1:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-tencent
```
hello1的service.yaml文件内容。
```
apiVersion: v1
kind: Service
metadata:  
  name: hello1
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  selector:   
    app: hello1
  ports:  
    - port: 3000
      targetPort: 3000
      protocol: TCP
```
注意，hello1要对cluster外部提供服务，type可以设置成NodePort，在ports设置项下面，nodePort不写端口号的时候，k8s会自动生成一个节点端口号。
#### hello2的部署文件
hello2的deployment.yaml文件内容。
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
  namespace: default
  labels:
    app: hello2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello2
  template: 
    metadata: 
      labels: 
        app: hello2 
    spec:
      containers: 
      - name: hello2
        image: shgbit.tencentcloudcr.com/hello/hello2:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-tencent
```
hello2的service.yaml文件内容。
```
apiVersion: v1
kind: Service
metadata:  
  name: hello2
  namespace: default
spec:
  selector:   
    app: hello2
  ports:  
    - port: 3001
      targetPort: 3001
      protocol: TCP
```
注意，hello2仅对cluster内部提供服务，type设置成ClusterIP，如果没有设置type，默认就是ClusterIP。

#### 部署hello1
进入hello1目录。
创建deployment。
```
kubectl apply -f deployment.yaml   
```
创建结果：
```
deployment.apps/hello1 created
```
创建service。
```
kubectl apply -f service.yaml
```
创建结果：
```
service/hello1 created
```

#### 部署hello2
进入hello2目录。
创建deployment。
```
kubectl apply -f deployment.yaml   
```
创建结果：
```
deployment.apps/hello2 created
```
创建service。
```
kubectl apply -f service.yaml
```
创建结果：
```
service/hello2 created
```

#### 查看部署后的状态
显示部署后hello1和hello2已经运行的pod。
```
kubectl get pods

NAME                      READY   STATUS    RESTARTS   AGE
hello1-759f5c79c6-47jtk   1/1     Running   0          4h40m
hello1-759f5c79c6-m5rsk   1/1     Running   0          4h40m
hello2-97bfd5b4d-fs85v    1/1     Running   0          3m44s
hello2-97bfd5b4d-tsnls    1/1     Running   0          3m44s
```
STATUS这一列是运行状态，Running就代表至少容器已经运行起来，如果不是Running状态，可以执行下面这条pod描述命令查看pod的运行信息，失败的信息具体可以在执行结果的Events中看到。
```
kubectl describe pod hello1-759f5c79c6-47jtk
```
如果想看一下容器内，服务程序在控制台输出的内容可以执行日志显示命令进行查看。
```
kubectl logs -f hello1-759f5c79c6-47jtk
```

查看hello1 service的ip和端口信息。
```
kubectl describe service hello1
```
```
Name:                     hello1
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=hello1
Type:                     NodePort
IP Families:              <none>
IP:                       10.97.21.16
IPs:                      10.97.21.16
Port:                     <unset>  3000/TCP
TargetPort:               3000/TCP
NodePort:                 <unset>  30662/TCP
Endpoints:                172.17.0.3:3000,172.17.0.4:3000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

查看hello2 service的ip和端口信息。
```
kubectl describe service hello2
```
```
Name:              hello2
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app=hello2
Type:              ClusterIP
IP Families:       <none>
IP:                10.110.139.92
IPs:               10.110.139.92
Port:              <unset>  3001/TCP
TargetPort:        3001/TCP
Endpoints:         172.17.0.5:3001,172.17.0.6:3001
Session Affinity:  None
Events:            <none>
```

## 本地端口映射
将本地的9000端口映射的hello1 service的服务端口上，这里说的服务端口就是service.yaml中的ports.port。
```
kubectl port-forward service/hello1 9000:3000 &
```

## 执行，调用hello1的接口
第一次执行：
```
curl http://127.0.0.1:9000/api/hello1                 
```
执行结果：
```
Handling connection for 9000
{"requestServiceIp":"172.17.0.4","responseServiceIp":"172.17.0.5"}%                                                           
```
第二次执行：
```
curl http://127.0.0.1:9000/api/hello1
```
执行结果：
```
Handling connection for 9000
{"requestServiceIp":"172.17.0.4","responseServiceIp":"172.17.0.6"}%                                                           
```
