### ISSUE TITLE
k8s的最小调度单位是Pod而不是容器

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#41]
## 再总结下容器
容器就是对进程采用Namespace做隔离，用CGroups做资源限制，用DeviceMapper等存储驱动管文件存储，用rootfs映射文件系统，这就是大名顶顶的容器。

## 容器的进程模型
容器是单进程模型，不是说一个容器就只能对应一个进程，所谓的单进程模型是指容器没有管理多个进程的能力。
多个进程的管理能力体现在：
1. 搞一个运行web服务的镜像，容器跑起来后，在容器内手动再跑一个nginx，有nginx对容器外部提供web服务的反向代理，如果nginx挂掉了，对外的代理就会断掉，站在容器角度是不知道nginx，也不会有后续重启等操作。要多进程协同工作，必须依靠进程自身的代码去生成子进程，并且管理子进程，比如nodejs的cluster。
2. 进程工作并非就是独立的，往往会需要几个进程协同完成工作，所以系统中还有进程组的概念，多个进程之间共享信号，进程间通信，共享文件，使用容器将各个进程打包在内，关键是要确保他们在一台主机上。
>进程组就是一组进程的集合，向一个进程发送信号，在组内的其他进程都会收到相同信号，在系统中进程组往往和会话绑在一起，一个会话的ID就是进程组中leader进程的PID，方便管理进程的创建，销毁。比如使用tty登录一个系统，登录后，启动shell时将会创建新的会话，shell进程会作为会话的的leader进程，随后shell里面运行的进程都将属于这个会话，当shell退出后，所有该用户运行的进程将退出。会话的leader进程会成为tty的控制进程，当会话的前端进程组发生变化时，控制进程负责更新tty上关联的前端进程组，当tty要关闭的时候，控制进程所在会话的所有进程都会收到SIGHUP信号。

## 使用容器为调度单位的问题-成组调度
假设做三个容器，分别是：main，work1，work2。
假设有两个，分别是：node1（内存资源给三个容器不够），node2（内存资源给三个容器够）。
不用k8s，而用Docker Swarm就能看出差异。
要求是这三个容器因为相互之间要进行进程间通信、共享文件，所以必须部署在同一台主机上，所以work1和work2的亲密性设置affinity=main。
顺序执行：`"docker run main" "docker run work1" "docker run work2"`。
创建容器后，进入Swarm调度序列，在将main、work1调度到node1上之后，发现node1上剩余的内存资源已经不足以再调度work2了，但是按照亲密性要求，work2又必须调度到node1之上，结果就work2的调度报错，main和work1也不能正常运行。
这就是一个典型的成组调度问题。

## k8s的成组调度解决方案就是以pod为单位
在k8s中，pod是最小的调度单位，pod又可以包含多个容器，在调度的时候必须按照pod的资源需求进行调度计算，这样的话，在上面的案例中，三个容器就属于同一个pod，在调度前通过计算pod的内存资源需求就会发现node1的资源是不够的，node2才符合要求，那么就会将pod直接调度到node2上。这就是pod存在的一个很重要的结果。
还有为什么现在说k8s是操作系统，也是因为它在容器领域实现了进程组这一概念。

### 网络共享
pod只是一个逻辑概念，k8s真正处理还是宿主机操作系统上Namespace和Cgroups，而并不存在一个所谓的pod的边界或者隔离环境，说白了pod就是一组共享了某些资源的容器。最常说的共享的资源就是Network Namespace和Volume。
问题就是两个容器如何共享Network Namespace，可以通过Join Network Namespace的方式让B容器的网络依赖于A容器的网络，但是这样就有个问题，那就是B的网络要可用，一定要先启动A，这样就造成两个容器不是对等的关系，A挂了，B的网络也就不通了。
k8s的解决方案：
<img width="483" alt="截屏2021-07-27 下午5 46 25" src="https://user-images.githubusercontent.com/8045042/127137591-de236b97-0ba4-486d-8c79-009b88c59571.png">

在图中可以看到，每个pod中都会预装一个infra容器，而且永远是第一个被安装的容器，它会提供一个Network Namespace，用户建的容器会执行Join Network Namespace加入到infra的网络中，意味着：
* 一个pod的ip地址就一个。
* 在pod中的容器看到的网络设备是一样的。
* 容器用localhost就可以相互访问。
* pod的生命周期由infra决定，并不是用户容器。
> Infra 容器一定要占用极少的资源，所以它使用的是一个非常特殊的镜像，叫作：k8s.gcr.io/pause。这个镜像是一个用汇编语言编写的、永远处于“暂停”状态的容器，解压后的大小也只有 100~200 KB 左右。

### volumn共享
正因为pod这一设计，pod内的容器都是部署在一个主机上，所以天然就具备对主机上相同目录的映射能力。
一个案列：
```
apiVersion: v1
kind: Pod
metadata:
  name: volumn-share-demo
spec:
  restartPolicy: Never
  volumes:
  - name: share-dir
    hostPath:      
      path: /page
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: share-dir
      mountPath: /home/nginx/html
  - name: build-container
    image: centos
    volumeMounts:
    - name: share-dir
      mountPath: /dist
    command: ["/bin/sh"]
    args: ["-c", "echo Hello World > /dist/index.html"]
```
可以看到先声明了一个volumn，并挂在到主机的`/page`目录下。
然后，build-container这个容器将主机目录`/page`挂载进自身容器目录`/dist`，并且执行命令生成一个hello world内容的html文件。
最后，nginx-container这个容器将主机目录`/page`挂载进自身容器目录`/home/nginx/html`，并且能够读到index.html这个文件。
以上就是volumn的共享。

## 总结
为什么是pod：
* 成组调度。
* 网络共享。
* volumn共享。
