### ISSUE TITLE
实践一下Grafana Loki

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#55]
# 前置工作
## 下载loki和promtail的config文件
```
wget https://raw.githubusercontent.com/grafana/loki/v2.4.2/cmd/loki/loki-local-config.yaml -O loki-config.yaml
docker run --name loki -v $(pwd):/mnt/config -p 3100:3100 grafana/loki:2.4.2 -config.file=/mnt/config/loki-config.yaml
wget https://raw.githubusercontent.com/grafana/loki/v2.4.2/clients/cmd/promtail/promtail-docker-config.yaml -O promtail-config.yaml
docker run -v $(pwd):/mnt/config -v /var/log:/var/log --link loki grafana/promtail:2.4.2 -config.file=/mnt/config/promtail-config.yaml
```
## 下载发生failed: Connection refused
注意：如果用上述wget下载config文件的时候发生`failed: Connection refused.`，需要配置下在地址的域名进行本地解析。

首先，打开`https://www.ipaddress.com/`页面。

输入`raw.githubusercontent.com`域名，进行解析，得到它对应的ip地址。

添加本地解析。
```
 sudo echo "185.199.108.133 raw.githubusercontent.com" >> /etc/hosts
```
然后再下载loki和promtail的config文件。

## 配置docker日志容量限制
```
sudo vi /var/snap/docker/current/config/daemon.json
```

```
{
  // 省略
  "log-driver": "local",
  "log-opts": {
    "max-size": "5m",
    "max-file": "3"
  }
}
```
```
sudo snap restart docker
```
```
sudo docker info
```

```
Logging Driver: local
```

# 方案一，采用promtail收集主机本地容器目录下的日志文件
## 采用docker-compose安装grafana、loki、promtail
获取docker-compose.yaml,里面包含grafana，loki，promtail的docker-compose.yaml文件。
```
wget https://raw.githubusercontent.com/grafana/loki/v2.4.2/production/docker-compose.yaml -O docker-compose.yaml
```
修改配置：
* loki的配置文件挂载到本地
* promtail的配置文件挂载到本地
* promtail收集的本地容器日志目录挂载到docker安装目录下的containers文件夹位置
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config:/etc/loki/config
    command: -config.file=/etc/loki/config/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - /var/log:/var/log
      - ./promtail/config:/etc/promtail/config
      - /var/snap/docker/common/var-lib-docker/containers:/etc/containers
    command: -config.file=/etc/promtail/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    networks:
      - loki

```
这个方案，虽然可以把所有的容器日志都收集进loki，但是很难去打合适的lable，所以查询很麻烦，没法按照容器名去查日志，这个方案先废弃。

# 方案二，采用Docker Driver Client收集日志
这个方案的好处，就是插件已经实现并默认为日志打上了包括container_name、host等label，方便存储、查询。
[官方配置参考](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/)。
## 安装[Docker Driver Client](https://grafana.com/docs/loki/latest/clients/docker-driver/#docker-driver-client)

```
docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
```

```
sudo docker plugin ls
```

```
ID             NAME          DESCRIPTION           ENABLED
2d59cba0f2eb   loki:latest   Loki Logging Driver   true
```

## 采用docker-compose安装grafana、loki，不装promtail
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config:/etc/loki/config
    command: -config.file=/etc/loki/config/loki-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    networks:
      - loki
```

启动
```
sudo docker-compose -f docker-compose-by-docker-driver.yaml up -d
```

## 观察Docker Driver Client plugin的日志
```
 sudo docker plugin inspect loki  | grep "\"Id\""
```
获取plugin的ID。
拿着Id去找日志。
```
sudo ls /run/docker/plugins/2d59cba0f2ebf2be01a46d7372a498901a7b742d3fba8e6c9243af8e8362cee6
```
显示
```
init-stderr  init-stdout  loki.sock
```
要看plugin的标准输出。
```
sudo cat /run/docker/plugins/2d59cba0f2ebf2be01a46d7372a498901a7b742d3fba8e6c9243af8e8362cee6/init-stdout
```

## 安装logcli（辅助使用）
```
wget https://github.com/grafana/loki/releases/download/v2.4.2/logcli-linux-amd64.zip
unzip logcli-linux-amd64.zip
```

```
export LOKI_ADDR=http://localhost:3100
```

## 配置应用容器，发送日志给loki
```
version: '3'

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"

  app-todo:
    container_name: app-todo
    image: registry.cn-shanghai.aliyuncs.com/space365/pilot-app-todo:latest
    environment:
      - BACKEND_BASE_URL=http://localhost/api/todo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-todo.entrypoints=web"
      - "traefik.http.routers.app-todo.rule=Host(`pilot365.io`)"
      - "traefik.http.routers.app-todo.rule=PathPrefix(`/app/todo`)"
      - 'traefik.http.routers.app-todo.middlewares=app-todo-stripprefix'
      - 'traefik.http.middlewares.app-todo-stripprefix.stripprefix.prefixes=/app/todo'
      - 'traefik.http.middlewares.app-todo-stripprefix.stripprefix.forceSlash=false'

  service-todo:
    container_name: service-todo
    image: registry.cn-shanghai.aliyuncs.com/space365/pilot-service-todo:latest
    ports:
      - "4000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.serive-todo.entrypoints=web"
      - "traefik.http.routers.serive-todo.rule=Host(`pilot365.io`)"
      - "traefik.http.routers.serive-todo.rule=PathPrefix(`/api/todo`)"
      - 'traefik.http.routers.serive-todo.middlewares=serive-todo-stripprefix'
      - 'traefik.http.middlewares.serive-todo-stripprefix.stripprefix.prefixes=/api/todo'
      - 'traefik.http.middlewares.serive-todo-stripprefix.stripprefix.forceSlash=false'
      - 'traefik.http.services.id.loadbalancer.server.port=4000'
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-batch-size: "5"
```
在需要发送日志的容器中配置上面的：
```
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-batch-size: "5"
```
配置后，启动容器。
```
sudo docker-compose up -d
```
打开浏览器访问`http://192.168.113.133:3000`，按照[官方步骤](https://grafana.com/docs/loki/latest/getting-started/grafana/)配置grafna后就可以开始查询日志。
需要查询容器的日志，只需要用LogQL语法在Qeury输入框中输入即可以查询容器的日志。
```
{container_name="service-todo"}
```
