### ISSUE TITLE
安装kong-gateway作为ingress controller

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#70]
# 目标
在kubenetes中安装kong-gateway，工作在无数据库模式，装完后，以Kubernetes Ingress Controller方式进行工作。
版本为Open Source（OSS）。
删除原有的ingress controller，比较简单，不展开。

# 准备
1.创建`kong`命名空间
```
kubectl create namespace kong
```

2.下载部署文件
部署文件地址：`https://bit.ly/kong-ingress-dbless`

注意，需要fq，服务器不方便的话，可以在已fq的电脑上用浏览器访问部署文件地址，并将页面上显示的部署内容保存到部署文件，再把文件上传至服务器上。

# 安装
通过部署文件安装kong-gateway。
```
kubectl apply -f all-in-one-dbless.yaml
```
安装后，看一下是否正常运行。
```
kubectl get pods -n kong
```

# 额外
1.kong装完后，它的Service的Type默认是LoadBalancer，私有化使用，方便起见，以NodePort方式暴露。
```
 kubectl -n kong patch service kong-proxy -p '{"spec":{"type":"NodePort"}}'
```

2.需要为服务创建ingress时，注意在ingress的ingressClassName上设置成kong。
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-todo
  namespace: pilot-dev
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - backend:
              service:
                name: svc-todo
                port:
                  number: 80
            path: /tasks
            pathType: Prefix
```

# 参考
[Install on Kubernetes](https://docs.konghq.com/gateway/3.0.x/install/kubernetes/kubectl/)
