### ISSUE TITLE
踩坑，Ingress的Host必须要填对了

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#71]
# 想干什么
想要在私有化的服务器上通过ingress把'/tasks'路由到相应的Service上，私有化环境没有域名，Ingress Controller用的是Nginx。
所以在创建ingress的时候，就没考虑在ingress中配置host。
另外，按照官方的[说明](https://kubernetes.io/zh-cn/docs/concepts/services-networking/ingress/#ingress-rules)，ingress的host是可选的，是可以不用写的，比如说下面这样写一个'ingress.yaml'。
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-todo
  namespace: pilot-dev
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: svc-todo
                port:
                  number: 80
            path: /tasks
            pathType: Prefix

```

# 现实如此
在使用`ingress.yaml`创建`ingress-todo`后，发现对‘/tasks’路由的访问总是报错404。
突然有点懵，懵在如此平常的配置，竟然报了404，问题出在哪里。
赶紧看了nginx-ingress的日志，看到了一个报错，其实是一个警告：

> <b>type: 'Warning' reason: 'Rejected' spec.rules[0].host: Required value</b>

看到这个报错，更懵了，路由被拒，是因为host没填，官方不是说可选的么，怎么又要填。
好吧，查呗，找找官方的Issue怎么说。
> [Ingress that works in ingress-nginx doesn't work with nginx-ingress #1324](https://github.com/nginxinc/kubernetes-ingress/issues/1324)
> [Support for not setting explicit host #209](https://github.com/nginxinc/kubernetes-ingress/issues/209)

好吧，按照Issue上的回复，Ingress的规范的要求上，host是可以选填，But！！！，Nginx不支持，限制说明和为什么限制在如下两个nginx ingress controller说明文档中。
> [nginx-ingress-controller/basic-configuration/restrictions](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/#restrictions)
> [Handling Host and Listener Collisions](https://docs.nginx.com/nginx-ingress-controller/configuration/handling-host-and-listener-collisions)

# 解决方法
按照Issue给出的建议，以及自身的实践，总是解决方案就是设置Host（废话！！！）。
为Ingress配上Host。
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-todo
  namespace: pilot-dev
spec:
  ingressClassName: nginx
  rules:
    - host: dev.pilot.cc
      http:
        paths:
          - backend:
              service:
                name: svc-todo
                port:
                  number: 80
            path: /tasks
            pathType: Prefix
```

Host配上了，调用怎么办。
两种办法：
* 调用API时带上Host。
* 前置一个nginx，在代理时带上Host参数再给到Ingress Controller。

<b>1. 调用API时带上Host。</b>
```
GET http://172.16.30.251:32427/tasks HTTP/1.1
Host: dev.pilot.cc
```

<b>2. 前置一个nginx，在代理时带上Host参数再给到Ingress Controller。</b>
```
upstream backend {
    server my-service;
}

server {
    listen 80 default_server;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
    }
}
```
