### ISSUE TITLE
APISIX实践，使用limit-req限制每秒接口访问量

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#74]
# 目标
* 对`/tasks`api进行rate limit限制
* 使用插件`limit-req`，限制每秒访问数量。

# 实现
* 为ApisixRoute配置plugin
* 应用ApisixRoute配置
* 测试限流效果

###  为ApisixRoute配置plugin
修`apisixRoute.yaml`，加上plugins配置项。
```
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: apisixroute-todo
  namespace: pilot-dev
spec:
  http:
  - name: rule-todo
    match:
      hosts:
      - dev2.pilot.cc
      paths:
      - /tasks
    backends:
       - serviceName: svc-todo
         servicePort: 80
    plugins:
      - name: limit-req
        enable: true
        config:
          rate: 1
          burst: 2
          nodelay: true
          rejected_code: 429
          key: 'remote_addr'
```
说明：
* plugins是一个数组，其下可以配置n个插件
* 每一个插件都要设置name，为插件名，这里写上`limit-req`
* enable设为true表示启用插件
* 每个插件的具体参数都配在config项目下
* rate配置成1，表示每秒钟只能请求一次API
* rejected_code表示触发限流时报错报的http响应码，429表示Too Many，一般用于Rate Limit

### 应用ApisixRoute配置
应用`apisixRoute.yaml`配置，启用插件。
```
sht@k3sk-server-01:~/pilot/todo$ kubectl -n pilot-dev apply -f apisixRoute.yaml
```
如果要看一下应用是成功，可以describe一下。
```
sht@k3sk-server-01:~/pilot/todo$ kubectl -n pilot-dev describe ApisixRoute apisixroute-todo
```

### 测试限流效果
快速多次调用`/tasks`API
```
GET http://172.16.30.251:32082/tasks HTTP/1.1
Host: dev2.pilot.cc
```
请求点的快了，就会触发Rate Limit，返回429错误。
```
HTTP/1.1 429 Too Many Requests
Date: Sat, 17 Dec 2022 16:44:49 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 241
Connection: Close
Server: APISIX/2.15.1
Proxy-Connection: Close

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
</html>
```

# 参考
[ApisixRoute](https://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2/)
[limit-req](https://apisix.apache.org/docs/apisix/plugins/limit-req/)
[ApisixRoute plugins configuration does not take effect](https://github.com/apache/apisix-ingress-controller/issues/532)
