### ISSUE TITLE
Kong Ingress Controller实践Part1，编排路由

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#76]
# 目标
利用httpbin、echo两个辅助服务，分别编排两个自定义路由，访问这两个服务，完成基本路由编排目标。

# 准备
部署两个帮助调试的上游服务
* httpbin 
* echo

### 部署httpbin服务
1. 下载部署文件，浏览器打开`https://bit.ly/k8s-httpbin`地址，将页面中的文件内容另存为部署文件`httpbin.yaml`，将部署文件上传指服务器。

2. 部署
```
sudo kubectl apply -f httpbin.yaml
```

### 部署echo服务
1. 准备镜像
echo的镜像是再`gcr.io`上，一般都是要翻墙才搞的到，所以，曲线一下，从docker.io上先拉下来，再改下tag。
```
sudo crictl pull registry-1.docker.io/e2eteam/echoserver:2.2
sudo ctr image tag registry-1.docker.io/e2eteam/echoserver:2.2 gcr.io/kubernetes-e2e-test-images/echoserver:2.2
```

2. 下载部署文件，浏览器打开`https://bit.ly/echo-service`地址，将页面中的文件内容另存为部署文件`echo-server.yaml`，将部署文件上传指服务器。

3. 部署
```
sudo kubectl apply -f echo-server.yaml
```

# 通过Kong Ingress Controller编排路由
1. 创建Ingress，编排`/foo`路由转发到httpbin服务上，编排`/bar`路由转发到echo服务上。
> 注解中加了一行`konghq.com/strip-path: "true"`意思是先把path去掉在把请求转发到服务。
> `ingressClassName`为`kong`，表示当前配置的Ingress由Kong Ingress Controller来解析和处理。
```
echo '
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /foo
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpbin
            port:
              number: 80
      - path: /bar
        pathType: ImplementationSpecific
        backend:
          service:
            name: echo
            port:
              number: 80
' | sudo kubectl apply -f -
```
2. 分别按照上面两个路由，发两个请求，能看到正常的响应内容。
> 请求发送的工具是VSCode + restclient
```
GET http://172.16.30.251:32736/foo/status/200 HTTP/1.1
GET http://172.16.30.251:32736/bar HTTP/1.1
```

# 参考
[Using KongPlugin resource](https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/guides/using-kongplugin-resource/)
