### ISSUE TITLE
Gitlab CI/CD实践，实现Jmeter分布式性能测试

### ISSUE THREAD

**Issue by bobenut** [bobenut/me#83]
#目标
* 创建Jmeter性能测试仓库
* 准备控制机（Master）和执行机（Slave）
* 实现CI脚本
* 执行

# 过程
## 创建Jmeter性能测试仓库
仓库目录结构：
![image](https://user-images.githubusercontent.com/8045042/226780760-c502c0ed-b66e-49ec-ac0a-fb236dce99f5.png)
更具不同的测试场景划分scenario，所有case对应的jmx脚本放在对应的scenario中。

## 准备控制机（Master）和执行机（Slave）
准备两台装有Windows10的电脑，一台即作为Master也作为Slave（最好是分开），另一台仅作为Slave。
按照[JMeter官方](https://jmeter.apache.org/usermanual/get-started.html)配置JAVA环境，JMeter版本采用5.5。
![image](https://user-images.githubusercontent.com/8045042/226781962-3101c7ad-d68b-4d36-9989-e4ab3968a7cf.png)

Slave的Jmeter关键配置，修改`jmeter.properties`相应配置：
```
remote_hosts=127.0.0.1
server_port=8899
server.rmi.ssl.disable=true
```

修改后，运行`jmeter-server.bat`。

## 实现CI/CD脚本
修改仓库中的`.gitlab-ci.ym`文件添加CI/CD脚本。
```
variables:
  REMOTE_HOSTS: "192.168.1.212:8899,192.168.1.76:8899" # 定义多个Slave的IP地址和jmeter.properties中配置的端口

stages:
  - test

lint-test-job:
  stage: test
  tags:
    - jmeter-win # 预期使用哪个Runner来执行CI/CD脚本，这里的tags配置成安装Runner时配置的tags
  before_script:
    - echo "before script"
  script:
    - echo "script"
    - dir    
    - echo $SCENARIO # 在run的时候需要指定仓库中scenario中的具体哪个，用于拼接成用例jmx文件地址
    - echo $CASE         # 在run的时候需要指定仓库中设置的scenario下面的jmx文件名，用于拼接成用例jmx文件地址
    - if ((Test-Path "result.jtl") -eq "True") {rm result.jtl} # 删除上一次执行报告
    - if ((Test-Path "result.log") -eq "True") {rm result.log} # 删除上一次日志
    - echo "jmeter -J remote_hosts=$REMOTE_HOSTS -J server.rmi.ssl.disable=true -n -t scenario\$SCENARIO\$CASE -r -l result.jtl -j result.log"
    - jmeter -J remote_hosts=$REMOTE_HOSTS -J server.rmi.ssl.disable=true -n -t scenario\$SCENARIO\$CASE -r -l result.jtl -j result.log
  when: manual
  artifacts:
    paths:
      - result.jtl # 测试完成后，将已汇聚的测试结果收集进Gitlab Artifacts，可以在执行完成后的页面上下载到
      - result.log
    expire_in: 2 days
```

## 执行
进入当前仓库中，从左侧的菜单开始，菜单 CI/CD -> Pipelines -> Run Pipeline。
在`Run pipeline`页面中，输入变量SCENARIO和CASE的字符串值写，比如要执行`scenario/scenario01/case-1.1.jmx`，那么变量SCENARIO就要设置成scenario01，变量CASE设置成case-1.1.jmx。
变量设置后可以Run pipeline了。
